import dash_core_components as dcc
import dash_html_components as html
import plotly.graph_objs as go
from dash.dependencies import Input, Output
import dash_table

from utils import Header, make_dash_table

import pandas as pd
import pathlib

def create_layout(app, params):
    # Page layouts
    return html.Div(
        [
            html.Div([Header(app)]),
            # page 1
            html.Div(
                [
                    # Row 3
                    html.Div(
                        [
                            html.Div(
                                [
                                    html.H5("Warning"),
                                    html.Br([]),
                                    html.P(
                                        'Contexts need to be obtained before move to Predictive Modeling.'
                                        ''
                                            .format(
                                            params["datasetdict"][params["dataname"]]),
                                        style={"color": "#ffffff"},
                                        className="row",
                                    ),
                                ],
                                className="product",
                            ),
                            html.Div([
                                dcc.ConfirmDialogProvider(
                                    children=html.Button(
                                        'Click here for more info.',
                                    ),
                                    id='danger-danger',
                                    message='List of all variables generated by XMAP \n' + str(params)
                                ),
                                html.Div(id='output')
                            ])
                        ],
                        className="row",
                    ),
                ],
                className="sub_page",
            ),
        ],
        className="page",
    )


